### PR TITLE
makes use of webhook secrets

### PR DESCRIPTION
**Pull request by jupyterkat**
also makes some stuff shared between two binaries

### CODE REVIEW

**Comment by AffectedArc07** [comment]
I need to TM this at some point

**Comment by optimumtact** [comment]
LGTM

**Comment by AffectedArc07** [comment]
This has ran fine in prod for 2 weeks or so, fine to merge if no one else objects.

**Comment by AffectedArc07** [comment]
Ran fine in prod for like 4 months

**Pull request merged**
